data-source:
  simulator:
    debug: 0
    initial-scale: "0"
    log-interval: 10s
    max-data-points: "0"
    max-metric-count: "100"
    scale: "2"
    seed: 0
    timestamp-end: "2020-01-02T00:00:00Z"
    timestamp-start: "2020-01-01T00:00:00Z"
    use-case: devops-generic
  type: SIMULATOR
loader:
  db-specific:
    use-qps-limiter: false
    limiter-max-qps: 400000
    limiter-bucket-size: 1200
    admin-db-name: postgres
    chunk-time: 12h0m0s
    create-metrics-table: true
    field-index: VALUE-TIME
    field-index-count: 0
    force-text-format: false
    host: localhost
    in-table-partition-tag: false
    log-batches: false
    partition-index: true
    partitions: 1
    pass: "password"
    port: "5432"
    postgres: sslmode=disable
    time-index: true
    time-partition-index: false
    use-hypertable: true
    use-jsonb-tags: false
    user: postgres
    write-profile: ""
    write-replication-stats: ""
  runner:
    batch-size: "10000"
    channel-capacity: "0"
    db-name: benchmark
    do-abort-on-exist: false
    do-create-db: true
    do-load: true
    flow-control: false
    hash-workers: false
    insert-intervals: ""
    limit: "0"
    reporting-period: 10s
    seed: 0
    workers: "1"
  target: timescaledb
