data-source:
  simulator:
    debug: 0
    initial-scale: "0"
    log-interval: 10s
    max-data-points: "0"
    max-metric-count: "10"
    scale: "4000"
    seed: 0
    timestamp-end: "2021-01-30T11:58:00Z"
    timestamp-start: "2021-01-27T11:57:00Z"
    use-case: devops
  type: SIMULATOR
loader:
  db-specific:
    host: "localhost"
    port: "4141"
    send-batch-size: 1000
    use-qps-limiter: true
    limiter-max-qps: 200000
    limiter-bucket-size: 50
    is-validation-test: true
  runner:
    batch-size: "100"
    channel-capacity: "12"
    db-name: benchmark
    do-abort-on-exist: false
    do-create-db: true
    do-load: true
    flow-control: false
    hash-workers: false
    insert-intervals: ""
    limit: "0"
    reporting-period: 10s
    seed: 0
    workers: "100"
  target: kmon
