data-source:
  simulator:
    debug: 0
    initial-scale: "0"
    log-interval: 10s
    max-data-points: "0"
    max-metric-count: "100"
    scale: "1000"
    seed: 0
    timestamp-end: "2020-03-01T00:00:00Z"
    timestamp-start: "2020-01-01T00:00:00Z"
    use-case: iot
  type: SIMULATOR
loader:
  db-specific:
    backoff: 1s
    consistency: all
    gzip: true
    replication-factor: 1
    urls: http://localhost:8086
    use-qps-limiter: false
    limiter-max-qps: 400000
    limiter-bucket-size: 100000
  runner:
    batch-size: "1000"
    channel-capacity: "0"
    db-name: benchmark
    do-abort-on-exist: false
    do-create-db: true
    do-load: true
    flow-control: false
    hash-workers: false
    insert-intervals: ""
    limit: "0"
    reporting-period: 10s
    seed: 0
    workers: "6"
  target: influx
