data-source:
  simulator:
    debug: 0
    initial-scale: "0"
    log-interval: 10s
    max-data-points: "0"
    max-metric-count: "100"
    scale: "1000"
    seed: 0
    timestamp-end: "2020-01-02T00:00:00Z"
    timestamp-start: "2020-01-01T00:00:00Z"
    use-case: devops
  type: SIMULATOR
loader:
  db-specific:
    urls: http://localhost:8428/write
    limiter-bucket-size: 20000
    limiter-max-qps: "500000"
    use-qps-limiter: false
  runner:
    batch-size: "100"
    channel-capacity: "0"
    db-name: benchmark
    do-abort-on-exist: false
    do-create-db: true
    do-load: true
    flow-control: false
    hash-workers: false
    insert-intervals: ""
    limit: "0"
    reporting-period: 10s
    seed: 0
    workers: "8"
  target: victoriametrics
